version: "3.6"

services:
  app:
    image: ${IMAGE_APP}
    ports:
      - ${APP_PORT}:80
    volumes:
      - .env:/var/www/html/.env
    environment:
      SKIP_COMPOSER: 1
    links:
      - database

  database:
    image: ${IMAGE_DATABASE}
    volumes:
      - eva-auth-db:/var/lib/mysql
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    image: ${IMAGE_REDIS}

volumes:
  eva-auth-db:
